_target_: src.models.ACGAN
lr: 0.0001
output_dir: ${output_dir}
generator:
  _target_: src.models.ConditionalGenerator
  channels: 3
  img_size: 32
  n_classes: 10
  latent_dim: 100
discriminator:
  _target_: src.models.ConditionalDiscriminator
  channels: 3
  img_size: 32
  n_classes: 10
