_target_: src.models.DiffusionGan
lr: 0.0001
output_dir: ${output_dir}
generator:
  _target_: src.models.Generator
  channels: 3
  img_size: 32
  latent_dim: 100
discriminator:
  _target_: src.models.Discriminator
  channels: 3
  img_size: 32
  ada_interval: 4
  beta_schedule: linear
  beta_start: 0.0001
  beta_end: 0.02
  t_min: 10
  t_max: 1000
  noise_std: 0.05
  aug: no
  ada_maxp: null
  ts_dist: priority
