_target_: src.models.DiffusionWGAN
critic_iter: 5
lambda_term: 10
lr: 0.0001
output_dir: ${paths.output_dir}
generator:
  _target_: src.models.wgan.Generator
  channels: 3
  latent_dim: 100
discriminator:
  _target_: src.models.wgan.Discriminator
  channels: 3
ada_interval: 4
beta_schedule: linear
beta_start: 0.0001
beta_end: 0.02
t_min: 10
t_max: 1000
noise_std: 0.05
aug: no
ada_maxp: null
ts_dist: priority
